### ISSUE TITLE
How can i change the web panels port?

### ISSUE THREAD

**Issue by Schwarzeisc00l** [notthebee/ansible-easy-vpn#129]
I used the script and it works without any issues.
However i want to run Vaultwarden too and i failed to change the port of Vaultwarden.
I want to change wg.xxx.xxx.xxx.duckdns.org to wg.xxx.xxx.xxx.duckdns.org:90 or any other port.
How can i do that?

**Comment by notthebee** [comment]
This wouldn't be so easy, unfortunately.
Bunkerweb needs to run on the ports 80 and 443 in order to get Let's Encrypt certificates.
What you can do is edit the Bunkerweb config in the Ansible project to also add Vaultwarden as a proxy backend 
https://github.com/notthebee/ansible-easy-vpn/blob/main/roles/bunkerweb/templates/env.j2

I guess you wouldn't need to proxy it through Authelia, since Vaultwarden already supports 2FA. So the lines you'd need to add will look something like this:
```
vaultwarden_REVERSE_PROXY_URL=/
vaultwarden_REVERSE_PROXY_HOST=http://vaultwarden:vaultwarden-port
```

You'd also need to add the `vaultwarden` container to the `wg_network` network. No need to forward any ports.

**Comment by Schwarzeisc00l** [comment]
So if i got this right,
I need to add  these to the Bunkerweb config
> vaultwarden_REVERSE_PROXY_URL=/
> vaultwarden_REVERSE_PROXY_HOST=http://vaultwarden:vaultwarden-port

> You'd also need to add the vaultwarden container to the wg_network network. No need to forward any ports.

How can i do that?
I don't want you to personally help me but an article or a Stack Overflow post would be nice

**Comment by notthebee** [comment]
https://docs.docker.com/engine/reference/commandline/network_connect/

**Comment by Schwarzeisc00l** [comment]
` What you can do is edit the Bunkerweb config in the Ansible project to also add Vaultwarden as a proxy backend`
Where do i put that file?

**Comment by notthebee** [comment]
https://github.com/notthebee/ansible-easy-vpn/blob/main/roles/bunkerweb/templates/env.j2
