### ISSUE TITLE
[Question] which wireguard version is used?

### ISSUE THREAD

**Issue by cholzer79** [notthebee/ansible-easy-vpn#157]
Sorry for the question but as I have seen an issue on the wg-easy github page that it ships with an outdated version of wireguard I was wondering if you also use this outdated version - as well as if your auto-update also updates wireguard?

THX!

**Comment by notthebee** [comment]
Could you link me the issue?

**Comment by cholzer79** [comment]
> Could you link me the issue?

https://github.com/WeeJeWel/wg-easy/issues/206

**Comment by notthebee** [comment]
This might be not so tragic, since it's the `wireguard-tools` that has an old version, not Wireguard itself. Wireguard is built into the Linux kernel, so its version will depend on the kernel that you have installed. For example, on Rocky Linux 9:

```
root@ansible-easy-vpn:~# dmesg | grep wireguard
[  359.337753] wireguard: WireGuard 1.0.20201112 loaded. See www.wireguard.com for information.
[  359.337754] wireguard: Copyright (C) 2015-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
```

@WeeJeWel mentioned that updating the `wireguard-tools` package will break Raspberry Pi installations: https://github.com/WeeJeWel/wg-easy/pull/209#issuecomment-1153295879

**Comment by cholzer79** [comment]
> Wireguard is built into the Linux kernel, so its version will depend on the kernel that you have installed.

So if I use Debian and run your script, then it will use the Wireguard that is part of that kernel, not what ships with wg-easy, so I am always on a recent Wireguard vershion, correct?
 :)
