### ISSUE TITLE
Challenge failed for domain

### ISSUE THREAD

**Issue by mike11207** [notthebee/ansible-easy-vpn#164]
- [x] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [x] I've also searched through the existing issues, and my problem hasn't been brought up

**Describe the issue**
Upon entering my duckdns domain it runs certbot and runs some checks.
These checks fail:

Challenge failed for domain auth.wireguard-vpn.duckdns.org
wg.wireguard-vpn.duckdns.org
wireguard-vpn.duckdns.org

And

IMPORTANT NOTES

Error getting validation data

**Environment:**
- Client OS: Android, Windows, Linux
- VPS OS Debian 11
- VPS Provider none (self hosted)

**Comment by notthebee** [comment]
Since this is self-hosted, are you sure that the server is accessible to Let's Encrypt on the port 80?

**Comment by skbaji6** [comment]
same issue here.  its a bad idea to have 3 subdomains pointing to same ip. it is forcing to have a separate public ip for the system where we are installing this wire guard. remove the validation to check whether given domain is pointed to public ip or not.

**Comment by notthebee** [comment]
> it is forcing to have a separate public ip for the system where we are installing this wire guard
You need a public IP address in order for Wireguard to work. You need a domain name in order to get valid HTTPS certificates. Using a domain name is also pretty much the only way to connect to a Wireguard server that is behind a NAT and doesn't have a static IP address.

It seems that threre's a fundamental misunderstanding of how Wireguard works on your part.

> this check is unnecessary.
The check is there for a reason. It's not an 'issue', it's a safety mechanism that prevents people from having a broken setup.

Feel free to fork the script and remove the check. I won't be 'fixing' this.
