### ISSUE TITLE
Update docker containers

### ISSUE THREAD

**Issue by tomsteenbakkers** [notthebee/ansible-easy-vpn#173]
Are the docker containers also automatically being  updated?

Can you use WatchTower to enable automatic updates?

**Comment by notthebee** [comment]
The Docker container versions are pinned and updated centrally, by me.

Using watchtower or a similar automatic update system in a production environment is not a good idea, because updates tend to break things. I usually read release notes, test new container versions and push the changes to this repo when there are any notable updates. 

You can look at the commits here once every now and then, and do a `git pull` on your ansible-easy-vpn folders when there are updates.
