### ISSUE TITLE
Support for home server

### ISSUE THREAD

**Issue by aaronmee** [notthebee/ansible-easy-vpn#226]
**Is your feature request related to a problem? Please describe.**
I tried to install the VPN on my personal server using your playbook, but the installation failed. 
I guess it's because port 80 wasn't open for certbot. Do I have to open more ports except for 51820?

**Describe the solution you'd like**
So far, the playbook is intended only for VPS, right? It would be nice if there were local server support as well. This means for me that I only want to have to open port 51820 and no more. 

**Additional context**
I want to install the VPN on my server running Ubuntu Server 22.04
I only need to access the VPN from the internet, configuration can be done locally, so that I don't have to open more ports except for 51820

Is this possible? 
I love the idea of your playbook

**Comment by aaronmee** [comment]
Okay, thanks for explaining this. 
So there's no way to do it without opening these ports? Can I close the http ones afterward?

Then, in terms of security, with those three ports open, is your configuration safe to prevent unauthorized access to the local network?

Thanks for your help

**Comment by notthebee** [comment]
You can close the port 80 afterwards, but the port 443 will still be needed to manage the Wireguard client configs, since it's a WebUI. Moreover, you'll need to re-open the port 80 every time you need to renew the Let's Encrypt certificate.

The server sets up a basic firewall, but the security of your local network is entirely on you. If you don't isolate/firewall the VPN host from your network, and the attacker somehow finds a way to use your host as an entry point (e.g. a software vulnerability in SSH, Authelia or Wireguard), they will get access to your entire network.
