### ISSUE TITLE
How do I update containerized software such as wireguard, wg-easy, adguard, authelia?

### ISSUE THREAD

**Issue by rm76** [notthebee/ansible-easy-vpn#237]
This isn't really an issue, it's just that I'm not familiar with docker.
I know how to update software packages on Ubuntu (apt upgrade), but how do I go about updating containerized software?
What best practices should I follow to keep the VPS up to date in the long run?
Thanks!

**Comment by 0x09AF** [comment]
Wanted to ask the same. We probably all have the containers versions defined during the video creation.  
I am used to the `docker compose` style of upgrading, or watchtower, but not familiar with ansible.
What is the best way to upgrade containers?

**Comment by alexsammers1** [comment]
That would be amazing - cause the info available on other websites is not really helpful, and I'd love to be able to do that from my end.

I've just updated wg-easy since the software had a newer version - Updated to Node.js v18. - and now my wg dashboard goes to a 502 Bad Gateway nginx page, so I can't manage my devices. VPN itself has stopped working as well.

![Error](https://github.com/notthebee/ansible-easy-vpn/assets/19613171/4b7e148f-1915-4530-93de-6b47b8f4387c)

**Comment by notthebee** [comment]
Fixed in https://github.com/notthebee/ansible-easy-vpn/commit/146c32c763e0ba5843908c2a4c68f45d167d61e4
