### ISSUE TITLE
Error after running playbook

### ISSUE THREAD

**Issue by AyJeeBee** [notthebee/ansible-easy-vpn#243]
- [y] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [y] I've also searched through the existing issues, and my problem hasn't been brought up

**Describe the issue**
At the step run playbook after entering the vault password i recieve this error:

ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:

JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected key

The error appears to be in '/root/ansible-easy-vpn/secret.yml': line 1, column 28, but may
be elsewhere in the file depending on the exact syntax problem.

**Environment:**
- Client OS: [Linux]
- VPS OS [Ubuntu 22.04]
- VPS Provider [Digital Ocean]

**Comment by k-wlosek** [comment]
Check your Ansible Vault for syntax errors.

`ansible-vault edit secret.yml`
Enter your vault password. Valid YAML should look something like this:
```yaml
key: value

# ex.
user_password: abc

# or try denoting the string with quotes
user_password: "12av&W"
```
Do note that spaces and indentation are important in YAML.

**Comment by in2gee** [comment]
It looks like this could happen when user password contains quotes or any characters which can brake YAML syntax.
Script doesn't do any escaping, so in our particular case problem must be with " symbol.

@notthebee 
Escaping might help but since this password is used by multiple services it is better to limit using some special and spacing characters and single \ (which could just disappear in after reading)

**Comment by notthebee** [comment]
Fixed in https://github.com/notthebee/ansible-easy-vpn/commit/de1dfa3f0c6fc1e19369b84673fbfbd4bfbcccca
