### ISSUE TITLE
http not loading

### ISSUE THREAD

**Issue by Chinaboy5216** [notthebee/ansible-easy-vpn#25]
Hi Wolfgang,

so far finally got everything working except the WG WebUI.
When i enter the http address provided after the installation i get Server not found as result.

SSH over terminal and Remmina is working perfectly. 

Is there another way over cli to create QR codes and WG conf files to further test the functionality of the WG server?

**Comment by notthebee** [comment]
What do the Bunkerweb and Authelia logs say?
```
docker logs bunkerweb
docker logs authelia
```
Most likely, if you can't access the web server after the installation, it means that Let's Encrypt can't generate certificates (too many failures/wrong domain name/can't access port 80/etc.)
Sometimes, it can also indicate SMTP server misconfiguration (in case you've configured the e-mail functionality)

There's no way to access Wireguard via CLI as far as I know, and it kind of defeats the purpose of this playbook, since the whole point is the fancy WebUI with 2FA. If you're OK with accessing Wireguard via CLI, https://github.com/Nyr/wireguard-install might be a better option.

**Comment by Chinaboy5216** [comment]
getting errors in the bunkerwew logs: 

2022/07/25 08:28:01 [emerg] 51#51: cannot load certificate "/etc/letsencrypt/live/auth.MYSERVER/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/auth.MYSERVER/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/auth.MYSERVER/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/auth.MYSERVER/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)

authelia also shows an error in the logs:

time="2022-07-25T08:07:33Z" level=error msg="Failure running the user provider startup check: the system clock is not synchronized accurately enough with the configured NTP server" stack="github.com/authelia/authelia/v4/internal/commands/root.go:169 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:77  cmdRootRun\ngithub.com/spf13/cobra@v1.5.0/command.go:876                  (*Command).execute\ngithub.com/spf13/cobra@v1.5.0/command.go:990                  (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.5.0/command.go:918                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1571                                      goexit"

**Comment by Chinaboy5216** [comment]
Email i didn't configure so smtp should be ruled out normally

**Comment by notthebee** [comment]
Yep, your cert has failed to generate (likely because Let's Encrypt has throttled your domain bc of too many failed attempts) and it looks like your server clock is wrong.

I might be able to fix the NTP issue by including a step to synchronize time and date. Haven't thought about it yet bc I haven't seen this issue on a VPS yet

**Comment by Chinaboy5216** [comment]
my vps is located in the netherlands, i noticed in the script you use berlin. So timezone should be the same. Of course from where i access the site the time is different (+6 hours currently on your time in Germany)

**Comment by notthebee** [comment]
Just looked at the Authelia config and it looks like that's not an issue. NTP includes `disable_failure`, which means that the error is logged but doesn't halt the application.

**Comment by notthebee** [comment]
The timezone in inventory.yml is not actually used in Authelia

**Comment by Chinaboy5216** [comment]
ok then i guess i'll try maybe over another domain name or try aging tomorrow. I'll see, i will follow further the development of this script though, it's interesting!! Thanks again Wolfgang, learned some things again. I'll close this issue also.

**Comment by notthebee** [comment]
You're welcome – thanks for sticking with it and reporting bugs <3

**Comment by arsaces7** [comment]
> ok then i guess i'll try maybe over another domain name or try aging tomorrow. I'll see, i will follow further the development of this script though, it's interesting!! Thanks again Wolfgang, learned some things again. I'll close this issue also.

did you figured it out?
