### ISSUE TITLE
How to disable email functionality?

### ISSUE THREAD

**Issue by displyypeterson** [notthebee/ansible-easy-vpn#267]
- [x] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [x] I've also searched through the existing issues, and my problem hasn't been brought up

**Describe the issue**
I accidentally said Y on the email part. How to disable this again?

**Environment:**
- Client OS: Linux 
- VPS OS Debian 12
- VPS Provider Tempest

**Comment by displyypeterson** [comment]
Thanks, altough I am new to linux. Would you please help me on how to do this?

**Comment by notthebee** [comment]
```
cd $HOME/ansible-easy-vpn
ansible-vault edit secret.yml
# remove the line that starts with "email_password"
sudo bash bootstrap.sh
```

**Comment by displyypeterson** [comment]
How can I save the file when I am in ansible-vault edit secret.yml

**Comment by notthebee** [comment]
Sorry, I think you're missing some basic knowledge of Linux CLI that is needed to run this project. Please refer to the manual of the text editor that you're using.

I'll be closing this issue, since the steps to disable the e-mail functionality are outlined in the FAQ: https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md#q-my-smtp-credentials-are-correct-but-i-still-get-the-http-500-error-and-the-authelia-logs-show-an-io-timeout-error
