### ISSUE TITLE
Prompt not showing, SSH key is missing.

### ISSUE THREAD

**Issue by eepytofu** [notthebee/ansible-easy-vpn#3]
```
PS C:\Users\user> scp -P 22 root@0.0.0.0:/tmp/id_ssh_ed25519 ~/.ssh/id_vpn_user
~/.ssh/id_vpn_user: No such file or directory
```

**Comment by notthebee** [comment]
You're loading a key named `id_rsa`, but then the shell sayd `id_vpn_user: No such file or directory`
Did you change the key name to hide your username before pasting the command here, or is there something I'm missing?

**Comment by 8mpty** [comment]
> i ran the command in PowerShell, i didn't change the SSH key name but i did change some of the command that i pasted here to hide my username and server ip.

i too had the same issue and have posted my solution on the youtube vide but i'll just leave it here aswell:

ssh -p 22 empty@192.210.200.28 -i C:\Users\EmptyDesktop\.ssh\id_vpn_empty\id_ssh_ed25519

since i'm using windows, some commands does not work for me ex.

*ssh -P 22 <YourName>@<VPS IP> -i ~/.ssh/id_vpn_<name>*

I had to change it to *ssh -P 22 <YourName>@<VPS IP> -i /Users/<username of desktop>/.ssh/id_vpn_<name>* (i had to create the folder before doing this but have not tried it before doing so.)

For connecting to it again i use *ssh -p 22 <YourName>@<VPS IP> -i /Users/<username of desktop>/.ssh/id_vpn_<name>/id_ssh_<whatever ID this is>* (can press TAB to auto complete).

This might be just an issue to me but if anyone else has this problem, you can follow the steps above.

Thank You

**Comment by 8mpty** [comment]
> i ran the command in PowerShell, i didn't change the SSH key name but i did change some of the command that i pasted here to hide my username and server ip.

since i'm using windows, some commands does not work for me ex.

*ssh -P 22 <YourName>@<VPS IP> -i ~/.ssh/id_vpn_<name>*

I had to change it to *ssh -P 22 <YourName>@<VPS IP> -i /Users/<username of desktop>/.ssh/id_vpn_<name>* (i had to create the folder before doing this but have not tried it before doing so.)

For connecting to it again i use *ssh -p 22 <YourName>@<VPS IP> -i /Users/<username of desktop>/.ssh/id_vpn_<name>/id_ssh_<whatever ID this is>* (can press TAB to auto complete).

This might be just an issue to me but if anyone else has this problem, you can follow the steps above.

Thank You

**Comment by 8mpty** [comment]
> > i ran the command in PowerShell, i didn't change the SSH key name but i did change some of the command that i pasted here to hide my username and server ip.
> 
> i have already posted my solution on the youtube video but will leave it here aswell:
> 
> since i'm using windows, some commands does not work for me ex.
> 
> _ssh -P 22 @ -i ~/.ssh/id_vpn__
> 
> I had to change it to _ssh -P 22 @ -i /Users//.ssh/id_vpn__ (i had to create the folder before doing this but have not tried it before doing so.)
> 
> For connecting to it again i use _ssh -p 22 @ -i /Users//.ssh/id_vpn_/id_ssh__ (can press TAB to auto complete).
> 
> This might be just an issue to me but if anyone else has this problem, you can follow the steps above.
> 
> Thank You

some commands were removed by github (idk why) but you can just find it in the youtube comment section. (CTRL + F)
