### ISSUE TITLE
Email Address?

### ISSUE THREAD

**Issue by Jestre** [notthebee/ansible-easy-vpn#31]
Good afternoon,

Just discovered this, set up a VPS, went through the process and I am now at the Authelia login screen.  I set up email to send via Mailgun, so I entered all of the credentials when asked, but at no time did it ask me for my (a recipient) email address.  So when I click register device on the Authelia screen, it says it sends an email, but I am not sure to where.

And since I added email crews, the `show_2fa` command shows a "file not found" type error.

Any ideas?  Or just rebuild the whole thing without email?

J

**Comment by notthebee** [comment]
Hello,

It's an oversight on my part – the recipient address is the same as the sender address, since that's how I do it.

I will fix it in a future build, but for now, what you can do is edit this file: `/opt/docker/authelia/users_database.yml` and change the e-mail`. Make sure to stop the authelia container before with `docker stop authelia`, and start it back up after you've edited the file: `docker start authelia`

**Comment by Jestre** [comment]
That worked, thank you!  

I wasn't redirected (even after signing out and back in), but going to wg.domain in the browser window took me to the New Client spot.

I appreciate the quick response!

**Comment by notthebee** [comment]
Yep, that is a known issue on the Authelia side: https://github.com/authelia/authelia/issues/1711

**Comment by james-d-elliott** [comment]
@notthebee this is inaccurate. @Jestre this is most likely a bug with nginx stripping `&` chars from URLs. Can be overcome using the Set Misc modules `set_escape_uri`. If this is not the case if FetchAPI is being used it's not configured to appropriately follow redirects, if XHR's are being used then the only resolution is to use FetchAPI instead of XHRs.
