### ISSUE TITLE
just doesn't work!

### ISSUE THREAD

**Issue by wollygosling** [notthebee/ansible-easy-vpn#82]
help😐
I finished the process like the video except minor differences because of using windows.I used these commands from github  
scp -P 22 root@<server-ip-address>:/tmp/id_ssh_ed25519 C:\Users\<username>\.ssh
ssh -p 22 <username>@<server-ip-address> -i C:\Users\<username>\.ssh\id_ssh_ed25519(in this line there are two usernames that are not same , am I right?)
everything looks right but when I use wireguard to connect to vpn it just doesn't work.(button successfully  changes from deactivated to activated but nothing connects to internet)
I live in Iran and we have very limited internet. can this be the cause of problem?.
thank you for reading this comment.

**Comment by wollygosling** [comment]
this vpn didn't work on two different internet providers. Today I tested this vpn on another internet provider and worked😐.
interesting thing is that I could connect to server by ssh root @ server ip address command in powershell before setting vpn up with both of the internet providers that now doesn't connect to vpn.

**Comment by notthebee** [comment]
Your provider might be blocking the Wireguard port (51820). You can try changing it by putting `wireguard_port: 12345` (or any 5-digit number) in the `custom.yml` file before running the playbook.

**Comment by alexandrem2** [comment]
I had the same issue and tried correcting an error I got earlier when executing the playbook :
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
I went into the related file and commented the line 1573

However, having been through the playbook a first time I got stuck when I had to choose the Vault Password (the second time) because it wrote "ERROR ! input is already encrypted" and exited the playbook.

Is there a way to re-run the playbook ? Maybe deleting specific files and going through it again ?

**Comment by notthebee** [comment]
Yes – remove secrets.yml and custom.yml

**Comment by alexandrem2** [comment]
Sorry for the dumb question but where are these files located ?

**Comment by notthebee** [comment]
$HOME/ansible-easy-vpn

**Comment by alexandrem2** [comment]
Thank you. I was able to re-run the playbook but it exited before the setup of the ssh keys. I've been trying to do it manually (on my Windows machine) but I can't seem to make it work. 
When I try to do the command that copies the key it tells me ".ssh" doesn't exist when I've just created it

**Comment by notthebee** [comment]
You probably need to create the folder for the root user as well as the user you just created
